REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70590, 'Arak-arahm', 'Premiumbot');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70583, 'Serena', 'Premiumbot');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70577, 'Alexander', 'Premiumbot');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70572, 'Lyra', 'Premiumbot');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70563, 'Aragon', 'Premiumbot');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70557, 'Trugschluss', 'Premiumbot');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70555, 'Gandalf', 'Erzmagier');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70545, 'Baum', 'Weil Baum?!');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70465, 'Stefan', 'Todesritter');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70461, 'Zelda', 'Todesritterin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70459, 'Omi', 'Todesritterin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70458, 'Verena', 'Todesritterin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70456, 'Sliver', 'Todesritter');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70417, 'Frau Mettwurst', 'Druidin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70415, 'Alone', 'Druide');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70404, 'Teewurst', 'Druide');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70403, 'Frau Teewurst', 'Druidin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70402, 'Frau Leberwurst', 'Druidin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70401, 'Leberwurst', 'Druide');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70377, 'Uschi', 'Hexerin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70376, 'Herr Brutal', 'Hexer');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70369, 'Ursula', 'Hexerin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70368, 'Bob', 'Hexer');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70365, 'Richard', 'Hexer');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70336, 'Abfallbseitiger', 'Hexer');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70335, 'Ilse', 'Hexerin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70333, 'Murat', 'Magier');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70327, 'Sabrina', 'Magierin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70324, 'Julia', 'Magierin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70323, 'Walter', 'Magier');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70306, 'Isabella', 'Magierin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70265, 'Franzie', 'Schamanin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70261, 'Herr Steak', 'Schamane');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70259, 'Beate', 'Schamanin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70256, 'Schinkenwurst', 'Schamane');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70252, 'Firaliya', 'Schamanin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70239, 'Herr Hufe', 'Priester');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70227, 'Herr Schmerz', 'Priester');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70225, 'Herr Flausch', 'Priester');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70219, 'Herr Verdorben', 'Priester');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70180, 'Roxorine', 'Schurkin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70176, 'Roxxor', 'Schurke');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70169, 'Miss Schaden', 'Jägerin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70159, 'Shadow', 'Schurke');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70139, 'Andy', 'Jäger');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70133, 'Tina', 'Jägerin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70118, 'Iselda', 'Jägerin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70110, 'Frau Ekel', 'Jägerin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70069, 'Roffel', 'Paladin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70066, 'Dennis', 'Paladin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70060, 'Katarina', 'Paladine');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70053, 'Olaf', 'Paladin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70052, 'Brucharm', 'Paladin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70030, 'Ilsa', 'Kriegerin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70026, 'Hamma', 'Krieger');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70025, 'Ricarda', 'Kriegerin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70021, 'Kyra', 'Kriegerin');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70018, 'Kovo', 'Krieger');
REPLACE INTO `creature_template` (`entry`, `name`, `subname`) VALUES (70013, 'Grillgut', 'Krieger');

